//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
using System;

public class Program
{
    public static void Main(string[] args)
    {
        int sum = SumEvenFibonacciNumbers(10);

        Console.WriteLine(sum);
    }

    public static int SumEvenFibonacciNumbers(int max)
    {
        int currentFibNumber = 1;
        int firstFibNumber = 1;
        int secondFibNumber = 0;

        int sum = 0;
        while(currentFibNumber < max)
        {
            currentFibNumber = firstFibNumber + secondFibNumber;
            if(currentFibNumber % 2 == 0)
            {
                sum += currentFibNumber;
            }

            secondFibNumber = firstFibNumber;
            firstFibNumber = currentFibNumber;
        }

        return sum;
    }
}